name: Java CI - rodam v2 main

on: [push]
   
jobs:
  call-pipeline:
    uses: https://github.com/r4nd7/devops-pipe-rodo/blob/97cee657bd916f3610beceaba3eba7f3a1f87457/.github/workflows/main.yml@devops-pipe-rodo
