name: Java CI 

on: 
   workflow call
 jobs:
  build:
    runs-on: ubuntu-latest
    steps:
 
    - name: Chechout
      uses: actions/checkout@v3.5.3
     
    - name: Setup Java JDK
      uses: actions/setup-java@v3.12.0
      with:
       distribution: 'zulu'
       java-version: '11'

    - name: compile Gradle
      run: |
       chmod +x gradlew
       ./gradlew build
        
  
